### ISSUE TITLE
Error on npm start

### ISSUE THREAD

**Issue by dfcarpenter** [GordyD/3ree#1]
Keep getting an error with Bluebird on npm start and not sure why.

```
/Users/dan/js/3ree/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^

TypeError: Cannot read property 'each' of undefined
    at /Users/dan/Stringify/3ree/server/api/service/event.js:16:13
    at tryCatcher (/Users/dan/Stringify/3ree/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.errorAdapter (/Users/dan/Stringify/3ree/node_modules/bluebird/js/main/nodeify.js:36:34)
    at Promise._settlePromiseAt (/Users/dan/Stringify/3ree/node_modules/bluebird/js/main/promise.js:579:21)
    at Promise._settlePromises (/Users/dan/Stringify/3ree/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/dan/Stringify/3ree/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/dan/Stringify/3ree/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/dan/Stringify/3ree/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:371:17)
```

Also in the server directory the rethinkdb ip address is set to a 192\* address and not localhost (might be better to set this as localhost)

Anyways, nice work. Was thinking of using this very same stack for a new project!

**Comment by GordyD** [comment]
I'll update the config shortly. And add an installation section to the README.md

As for the issue. What version of Node are you running? I'll try to recreate.

**Comment by GordyD** [comment]
I just removed the database table that the system relies and recreated your issue. I'll add a script for setting up the local environment and update the repo! Thanks for the comment.

**Comment by dfcarpenter** [comment]
Yeah, I just realized that was the issue. I also added some code to setup the database and create the table. Thanks for checking in so fast!

**Comment by GordyD** [comment]
Hey. Just working on a branch to add in a utility for creating the database. See this [PR](https://github.com/GordyD/3ree/pull/3/files).
